name: taxigo
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^5.0.3
  firebase_auth: ^4.2.10
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^2.0.3
  geolocator: ^10.0.0
  internet_connection_checker: ^1.0.0+1
  provider: ^6.0.5
  yandex_geocoder: ^2.1.0
  yandex_mapkit: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: false

  assets:
    # API Keys
    - .env

    # Add assets from the images directory to the application.
    - assets/images/
    - assets/Logo Files/For Web/svg/White logo - no background.svg

  fonts:
    - family: Brand-Bold
      fonts:
        - asset: assets/fonts/bolt-semibold.ttf
    - family: Brand-Regular
      fonts:
        - asset: assets/fonts/bolt-regular.ttf
