name: taxigo
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: false

  # Enable generation of localized Strings from arb files.
  generate: false

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/Logo Files/For Web/svg/Color logo with background.svg

  fonts:
    - family: Brand-Bold
      fonts:
        - asset: assets/fonts/bolt-semibold.ttf
    - family: Brand-Regular
      fonts:
        - asset: assets/fonts/bolt-regular.ttf
